name: hello World
on: [push]
jobs:
  say_hello:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Say Hello
        run: echo "hello from GitHub Actions!"

      - name: Install dependencies
        run: python -m pip install pytest

      - name: Run tests
        run:  pytest test.py
